<!DOCTYPE html>
<html>
<head>
    <title>Download</title>
</head>
<body>
    <h1>filehosting</h1>

    <h2><?= $file->getOriginalName() ?></h2>

    <?php if (App\Model::isImage($file->getMimeType())) : ?>
        <img src="/<?= $file->getThumbnail() ?>">
    <?php endif; ?>

    <ul>
        <li>Size: <?= $file->getSize() ?></li>
        <li>Type: <?= $file->getMimeType() ?></li>

        <!-- mb somthing more -->
    </ul>

    <a href="<?= $router->pathFor('dwnld', ['id' => $file->getId()]) ?>">
        Download <?= $file->getOriginalName() ?>
    </a>
</body>
</html>