<!DOCTYPE html>
<html>
<head>
    <title>Download</title>
</head>
<body>
    <h1>filehosting</h1>

    <h2><?= $file->getOriginalName() ?></h2>

    <ul>
        <li>Size: <?= $file->getSize() ?></li>
        <li>Type: ...</li>

        <!-- mb somthing more -->
    </ul>

    <a href="/<?= $file->getPath() ?>/<?= $file->getNewName() ?>" download>
        Download <?= $file->getOriginalName() ?>
    </a>
</body>
</html>