<!DOCTYPE html>
<html>
<head>
    <title>filehosting</title>
    <link rel="stylesheet" type="text/css" href="/css/stylesheet.css">
</head>
<body>
    <h1>filehosting</h1>

    <form method="post" action="/" enctype="multipart/form-data">
        <input type="file" name="file">
        <input type="submit" name="submit">

        <?php if (isset($error) and $error != 0) : ?>
            <span><?php var_dump($error) ?></span>
        <?php endif; ?>

        <input type="hidden" name="<?= $csrfNameKey ?>" value="<?= $csrfName ?>">
        <input type="hidden" name="<?= $csrfValueKey ?>" value="<?= $csrfValue ?>">
    </form>

    <div class="dropzone">
        <p>Drop here</p>
    </div>

    <progress value="0" max="100"></progress>

    <ul>
        <?php foreach ($files as $file) : ?>
            <li>
                <a href="<?= $router->pathFor('download', ['id' => $file->getId()])?>">
                    <?= $file->getOriginalName() ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>

    <script type="text/javascript" src="/js/script.js"></script>
</body>
</html>