{% extends 'base.html' %}

{% block content %}
        {% if error is defined and error != 0 %}
            <div class="alert alert-danger" role="alert">
                Error code #{{ error }}
            </div>
        {% endif %}

        <form method="post" action="/" enctype="multipart/form-data">
            <input type="file" name="file">
            <button type="submit" class="btn btn-default">Submit</button>

            <input type="hidden" name="{{ csrfNameKey }}" value="{{ csrfName }}">
            <input type="hidden" name="{{ csrfValueKey }}" value="{{ csrfValue }}">
        </form>

        <div class="dropzone">
            Drop here
        </div>

        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"></div>
        </div>

        <ul class="list-unstyled files">
            {% for file in files %}
                <li>
                    <a href="{{ path_for('download', {'id': file.getId }) }}">
                        {{ file.getOriginalName }}
                    </a>
                </li>
            {% endfor %}
        </ul> 
{% endblock %}