{% extends 'base.html' %}

{% block content %}
        <form method="get" class="input-group" action="/search">
            <input type="text" class="form-control" name="q" value="{{ q }}">
            <span class="input-group-btn"><button type="submit" class="btn btn-default">Search</button></span>
        </form>

        <ul class="list-unstyled files">
            {% for file in files %}
                <li>
                    <a href="{{ path_for('download', {'id': file.getId }) }}">
                        {{ file.getOriginalName }}
                    </a>
                </li>
            {% endfor %}
        </ul> 
{% endblock %}