{% extends 'base.html' %}

{% block content %}
        <form method="get" class="clearfix" action="/search">
            <input type="text" class="form-control pull-left" name="q" value="{{ q }}">
            <button type="submit" class="btn btn-default pull-right">Submit</button>
        </form>

        <ul class="list-unstyled files">
            {% for file in files %}
                <li>
                    <a href="{{ path_for('download', {'id': file.getId }) }}">
                        {{ file.getOriginalName }}
                    </a>
                </li>
            {% endfor %}
        </ul> 
{% endblock %}